### PR TITLE
Build improvements for 1.7 changes

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
This PR will not work until https://github.com/OSC/ondemand/pull/87 is merged and tagged into latest or ci repos.

**Comment by treydock** [comment]
This PR should be good to go.

**Comment by johrstrom** [comment]
I have a rebase of this ready.  I'm happy to push it and carry this forward. More than the dependency updates (that have conflicts), I think the rpm updates a super valuable. 

Let me know.

**Comment by treydock** [comment]
Can rebase this branch if you want, or new PR , up to you.

**Comment by johrstrom** [comment]
Thanks! I just thought I'd take care of it, one less thing for you to do. I've pushed and am pulling this in now.

**Pull request merged**
